""" delete the user_type column from users  model

Revision ID: 5f6bf001aeb2
Revises: 46053bfec1c3
Create Date: 2024-06-27 12:11:29.680383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f6bf001aeb2'
down_revision = '46053bfec1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('user_type')
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', mysql.VARCHAR(length=50), nullable=False))
        batch_op.create_index('user_type', ['user_type'], unique=True)

    # ### end Alembic commands ###
